# Generated by Django 3.0.5 on 2020-08-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
